# This workflow will install Python dependencies and run DID document validation against the given schema file

name: did-schema-validation
on:
  push:
    branches: [ "main" ]

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    #strategy:
      #fail-fast: false

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8	# v5.0.0

    - name: Set up Python 
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
        
    - name: Run DID Document Validation
      env:
        DID_FILE: "v2/trustlist/did.json"
        SCHEMA_FILE: "schema/did-trustlist-schema.json"
      run: |
        python schema/did-json-schema-validation.py "$DID_FILE" "$SCHEMA_FILE"
